version: '3.7'

services:
  calendar-bot:
    container_name: calendar-bot
    hostname: calendar-bot
    build: 
      context: .
      dockerfile: Dockerfile
    image: calendar-bot:0.4.6
    restart: always
    volumes:
      - ./src/bwd:/usr/src/app/src/bwd
      - /usr/src/app/node_modules
    command: node src/app.js

  database:
    container_name: calendar-bot-database
    hostname: calendar-bot-database
    image: mongo:3.6
    restart: always
    volumes:
      - ./src/bwd/provider/mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: calendarbot