version: '3.7'

services:
  calendar-bot:
    container_name: calendar-bot
    hostname: calendar-bot
    build: 
      context: .
      dockerfile: prod.dockerfile
    image: calendar-bot:0.2.0
    restart: always
    environment:
      - ENV=production
