version: '3.7'

services:
  calendar-bot:
    container_name: calendar-bot
    hostname: calendar-bot
    build: 
      context: .
      dockerfile: dev.dockerfile
    image: calendar-bot:0.3.0
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - ENV=development
