version: '3.7'

services:
  calendar-bot:
    container_name: calendar-bot
    hostname: calendar-bot
    build: 
      context: .
      dockerfile: dev.dockerfile
    image: calendar-bot:0.3.0
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database

  database:
    container_name: calendar-bot-database
    hostname: calendar-bot-database
    image: rethinkdb:2.3.6
    restart: on-failure
    volumes:
      - ./src/bwd/provider/rethinkdb:/data
